// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nueofnserflssmnelrar.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im51ZW9mbnNlcmZsc3NtbmVscmFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIzOTAwODQsImV4cCI6MjA4Nzk2NjA4NH0.2JIn8wGodrzIMh2X5sxLlxr4erP7aCLkJ1qQc9RkKRg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});